import { chromium } from 'playwright';
const br=await chromium.launch(process.env.CHROMIUM? {executablePath:process.env.CHROMIUM} : (await import('node:fs')).existsSync('/opt/pw-browsers/chromium')? {executablePath:'/opt/pw-browsers/chromium'} : {});
const ctx=await br.newContext({viewport:{width:1280,height:900}, permissions:['clipboard-read','clipboard-write']}); const pg=await ctx.newPage(); const errs=[]; pg.on('pageerror',e=>errs.push('PAGEERROR '+e.message));
let fails=0; const ok=(n,c)=>{ if(!c) fails++; console.log((c?'✓ ':'✗ ')+n); };
const paste=(text)=>pg.evaluate((text)=>{ const dt=new DataTransfer(); dt.setData('text/plain',text); document.activeElement.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true})); },text);
const PHP=`class CompleteLoginController extends Controller\n{\n    public function __invoke(string $token): RedirectResponse\n    {\n        $userId = Cache::pull("oauth_login:{$token}");\n        if (! $userId) {\n            return redirect()->route('login')->withErrors(['email' => __('Посилання недійсне.')]);\n        }\n        Auth::login(User::findOrFail($userId));\n        return redirect()->intended('/');\n    }\n}`;
const SQL=`SELECT n.id, n.title, count(b.id) AS blocks\nFROM notes n LEFT JOIN blocks b ON b.note_id = n.id\nWHERE n.updated_at > now() - interval '7 days'\nGROUP BY n.id ORDER BY blocks DESC LIMIT 20;`;
await pg.goto(new URL('../index.html', import.meta.url).href); await pg.waitForTimeout(300); await pg.waitForTimeout(400); await pg.evaluate(()=>new Promise(r=>{ localStorage.clear(); const q=indexedDB.deleteDatabase('sheet'); q.onsuccess=q.onerror=q.onblocked=()=>r(); })); await pg.reload(); await pg.waitForTimeout(300);
await pg.mouse.click(420,300); await paste(PHP); await pg.waitForTimeout(150); await pg.mouse.move(1200,850); await pg.waitForTimeout(150);
const cb=pg.locator('.blk.is-code').first();
ok('1 порожня назва: підказка невидима без наведення', await cb.locator('.ctitle').evaluate(e=>e.textContent==='' && getComputedStyle(e,'::before').opacity==='0'));
await cb.locator('.cblk').hover(); await pg.waitForTimeout(150);
ok('2 при наведенні підказка «Назва блока…» видима', await cb.locator('.ctitle').evaluate(e=>getComputedStyle(e,'::before').opacity==='1' && getComputedStyle(e,'::before').content.includes('Назва блока')));
await cb.locator('.ctitle').click(); await pg.keyboard.type('CompleteLoginController.php'); await pg.keyboard.press('Enter'); await pg.waitForTimeout(400);
ok('3 назва набрана, Enter завершує, код лишився тільки для читання', (await cb.locator('.ctitle').textContent())==='CompleteLoginController.php' && await cb.evaluate(e=>e.querySelector('.cblk').classList.contains('locked') && document.activeElement!==e.querySelector('.ctitle')));
ok('4 назва стала заголовком нотатки в панелі', (await pg.locator('.item .it-t').first().textContent())==='CompleteLoginController.php');
await pg.reload(); await pg.waitForTimeout(400);
ok('5 назва збережена після перезавантаження', (await pg.locator('.blk.is-code .ctitle').first().textContent())==='CompleteLoginController.php');
{ const c=await pg.locator('.blk.is-code .cblk').first().boundingBox(), t=await pg.locator('.blk.is-code .ctitle').first().boundingBox();
  ok('5b назва по центру шапки (зсув '+Math.round((t.x+t.width/2)-(c.x+c.width/2))+'px)', Math.abs((t.x+t.width/2)-(c.x+c.width/2))<=2);
  const rz=await pg.locator('.blk.is-code .rz').first().boundingBox(); await pg.mouse.move(rz.x+9,rz.y+9); await pg.mouse.down(); await pg.mouse.move(rz.x+9-(c.width-320), rz.y+9,{steps:8}); await pg.mouse.up(); await pg.waitForTimeout(400);
  const c2=await pg.locator('.blk.is-code .cblk').first().boundingBox(), t2=await pg.locator('.blk.is-code .ctitle').first().boundingBox(), l2=await pg.locator('.blk.is-code .lang').first().boundingBox();
  ok('5c на вузькій картці ('+Math.round(c2.width)+'px) назва переходить у власний рядок під мовою', t2.y>l2.y+l2.height-2 && t2.width>c2.width*0.8);
  const rz2=await pg.locator('.blk.is-code .rz').first().boundingBox(); await pg.mouse.dblclick(rz2.x+9,rz2.y+9); await pg.waitForTimeout(300); }
await pg.mouse.click(420,640); await paste(SQL); await pg.waitForTimeout(150);
const cb2=pg.locator('.blk.is-code').nth(1); await cb2.locator('.ctitle').click(); await pg.keyboard.type('Топ нотаток за тиждень'); await pg.keyboard.press('Escape'); await pg.waitForTimeout(400);
await pg.fill('#q','тиждень'); await pg.waitForTimeout(300);
ok('6 пошук знаходить нотатку за назвою блока', (await pg.locator('.item').count())===1 && /<mark>тиждень<\/mark>/.test(await pg.locator('.item').first().innerHTML()));
await pg.fill('#q',''); await pg.waitForTimeout(200);
await cb2.locator('.copy').click(); await pg.waitForTimeout(150); const clip=await pg.evaluate(()=>navigator.clipboard.readText().catch(()=>''));
ok('7 копіюється лише код, без назви', clip.startsWith('SELECT') && !clip.includes('Топ нотаток'));
await pg.mouse.move(10,10); await pg.evaluate(()=>window.scrollTo(0,0)); await pg.waitForTimeout(150); await pg.screenshot({path:'app-title-light.png',clip:{x:280,y:0,width:1000,height:900}});
await pg.locator('#themeBtn').click(); await pg.locator('#themeBtn').click(); await pg.waitForTimeout(200); await cb.locator('.cblk').hover(); await pg.waitForTimeout(150); await pg.screenshot({path:'app-title-sand.png',clip:{x:280,y:200,width:1000,height:640}});
await pg.locator('#themeBtn').click(); await pg.waitForTimeout(100);
await pg.setViewportSize({width:390,height:844}); await pg.waitForTimeout(400); await pg.screenshot({path:'app-title-mobile.png'});
console.log(errs.length? errs.join('\n') : '✓ без помилок'); await br.close(); process.exit(fails||errs.length?1:0);
